"""Original Image Fokder Directory
Resized 된 Image Size
> 150x150
"""

masterOrigin = "image_origin/" # Original Image
masterResize = "image_real/" # Resized Image
# 현재 150x150 크기로 되어있음

master = masterResize

img_ori = "image/"
img_cat = "image_cat/"
img_kong = "image_kong/"
img_se = "image_se/"
img_arti = "image_artist/"
img_artidlc = "image_artist_dlc/"

# 새로운 이미지 있을 때
new_pict_dir = {
    "blackbunny.png": f"{master}{img_se}blackbunny.png",
    "cayangkelkel.png": f"{master}{img_se}cayangkelkel.png",
    "cowbrain.png": f"{master}{img_se}cowbrain.png",
    "cromanyum.png": f"{master}{img_se}cromanyum.png",
    "dukiki.png": f"{master}{img_se}dukiki.png",
    "hahanumatan.png": f"{master}{img_se}hahanumatan.png",
    "imnotcry.png": f"{master}{img_se}imnotcry.png",
    "jungnahurt.png": f"{master}{img_se}jungnahurt.png",
    "kukkk.png": f"{master}{img_se}kukkk.png",
    "kunkelkel.png": f"{master}{img_se}kunkelkel.png",
    "orehaha.png": f"{master}{img_se}orehaha.png",
    "prokelintroduce.png": f"{master}{img_se}prokelintroduce.png",
    "prokelkel.png": f"{master}{img_se}prokelkel.png",
    "whitebunny.png": f"{master}{img_se}whitebunny.png",
    "yohoho.png": f"{master}{img_se}yohoho.png",
}

# Picture Directory
pict_dir = {
    # 오리지날 로아콘
    "[ㅋㅋㅋ": f"{master}{img_ori}zzz.png",
    "[뀨": f"{master}{img_ori}ku.png",
    "[놀자에몽": f"{master}{img_ori}playmong.png", 
    "[놀자에요": f"{master}{img_ori}playtogeth.png", 
    "[눈물팡": f"{master}{img_ori}sosaaaadd.png", 
    "[두렵다": f"{master}{img_ori}afraid.png", 
    "[멈춰": f"{master}{img_ori}stop.png", 
    "[모무룩": f"{master}{img_ori}saaddd.png", 
    "[멘탈": f"{master}{img_ori}mental.png", 
    "[못참지": f"{master}{img_ori}cannot.png", 
    "[문열어": f"{master}{img_ori}openthedoor.png", 
    "[물음표": f"{master}{img_ori}whaaat.png", 
    "[물끄럼": f"{master}{img_ori}lookstraight.png",
    "[방긋": f"{master}{img_ori}banguht.png",
    "[빛": f"{master}{img_ori}light.png",
    "[빠직": f"{master}{img_ori}bazik.png",
    "[신나": f"{master}{img_ori}happpy.png",
    "[슬퍼": f"{master}{img_ori}sad.png",
    "[안줘": f"{master}{img_ori}nogive.png",
    "[영차": f"{master}{img_ori}cheerup.png",
    "[웃기구요": f"{master}{img_ori}sofunny.png",
    "[웃프네요": f"{master}{img_ori}funbutnotfun.png",
    "[추천": f"{master}{img_ori}suggestion.png",
    "[멋쩍": f"{master}{img_ori}museok2.jpg",
    "[뭐라고요": f"{master}{img_ori}whatyousay.png",
    "[이이잉": f"{master}{img_ori}yiiiing.png",
    "[정말이요": f"{master}{img_ori}really.png",
    "[줘": f"{master}{img_ori}giveme.png",
    "[머쓱": f"{master}{img_ori}museok.png",
    "[좋아요": f"{master}{img_ori}good.png",
    "[죽은척": f"{master}{img_ori}notdeath.png",
    "[짝짝": f"{master}{img_ori}clapclap.png",
    "[침묵": f"{master}{img_ori}nocomment.png",
    "[호에엥": f"{master}{img_ori}wooow.png",
    "[핥짝": f"{master}{img_ori}hehheh.png",
    "[헤헷": f"{master}{img_ori}hahat.png",
    "[히죽": f"{master}{img_ori}smile.png",
    
    # 냥바타콘
    "[냥웃음": f"{master}{img_cat}cat_smile.png", 
    "[냥짱": f"{master}{img_cat}cat_zzang.png", 
    "[냥녹음": f"{master}{img_cat}cat_meltdown.png", 
    "[냥좌절": f"{master}{img_cat}cat_discouragement.png", 
    "[냥힘내": f"{master}{img_cat}cat_cheerup.png", 
    "[냥부끄": f"{master}{img_cat}cat_shy.png", 
    "[냥냥펀치": f"{master}{img_cat}cat_punch.png", 
    "[냥브이": f"{master}{img_cat}cat_V.png",
    "[냥죽은척": f"{master}{img_cat}cat_notdeath.png",
    "[냥으음": f"{master}{img_cat}cat_ummmm.png",
    "[냥도로롱": f"{master}{img_cat}cat_dororong.png",
    "[냐앗호": f"{master}{img_cat}cat_yeah.png",
    "[냥허그": f"{master}{img_cat}cat_hearthug.png",
    "[냥츄릅": f"{master}{img_cat}cat_heee.png",
    "[냥행복": f"{master}{img_cat}cat_happy.png",
    "[냥멈춰": f"{master}{img_cat}cat_stopbadthing.png",
    "[냥치킨": f"{master}{img_cat}cat_chicken.png",
    "[냥슬퍼": f"{master}{img_cat}cat_sad.png",
    "[냥다닥": f"{master}{img_cat}cat_run.png",
    "[부끄럽냥": f"{master}{img_cat}cat_shyee.png",
    "[냥ㅋㅋ": f"{master}{img_cat}cat_haha.png",
    "[냐아아": f"{master}{img_cat}cat_haaaappppyy.png",
    "[냐호": f"{master}{img_cat}cat_yahoo.png",
    "[냥배부름": f"{master}{img_cat}cat_full.png",
    "[냥냠냠": f"{master}{img_cat}cat_yumyum.png",
    "[냥냥": f"{master}{img_cat}cat_meow.png",
    "[냥먼산": f"{master}{img_cat}cat_farmountain.png",
    "[냥쭈압": f"{master}{img_cat}cat_yummycat.png",
    "[냥꾹": f"{master}{img_cat}cat_push.png",
    "[쭈아압": f"{master}{img_cat}cat_sqeeeze.png",
    "[찰떡냥": f"{master}{img_cat}cat_chaltuk.png",
    
    # 응애 모코콩
    "[감사콩": f"{master}{img_kong}thankyou.png",
    "[꺼억콩": f"{master}{img_kong}fullkong.png",
    "[냠냠콩": f"{master}{img_kong}nyamyanmkong.png",
    "[노래콩": f"{master}{img_kong}songkong.png",
    "[더줘콩": f"{master}{img_kong}givememorekong.png",
    "[도망콩": f"{master}{img_kong}runkong.png",
    "[물줘콩": f"{master}{img_kong}waterme.png",
    "[뿅콩": f"{master}{img_kong}ppongkong.png",
    "[씨익콩": f"{master}{img_kong}zkong.png",
    "[잘자콩": f"{master}{img_kong}goodnightkong.png",
    "[촉촉콩": f"{master}{img_kong}sadkong.png",
    "[츄릅콩": f"{master}{img_kong}yummykong.png",
    
    # # 도화가콘
    # "[아가...": f"{master}{img_arti}",
    # "[아가놀자에요": f"{master}{img_arti}1appear.png",
    # "[아가쫑긋": f"{master}{img_arti}2chonggutt.png",
    # "[아가방긋": f"{master}{img_arti}3baggoom.png",
    # "[아가추": f"{master}{img_arti}4artistrecommend.png",
    # "[아가비추": f"{master}{img_arti}5artistnorecommnd.png",
    # "[아가틀": f"{master}{img_arti}6oldman.png",
    # "[아가찐": f"{master}{img_arti}7artistreal.png",
    # "[아가쌀": f"{master}{img_arti}8artistrice.png",
    # "[아가헿": f"{master}{img_arti}9artisthahat.png",
    # "[아가점프": f"{master}{img_arti}10artistjump.png",
    # "[아가랄라": f"{master}{img_arti}11artisthehe.gif",
    # "[아가환문": f"{master}{img_arti}12artistscanthehole.png",
    # "[아가여기": f"{master}{img_arti}13artistimhere.png",
    # "[아가나쁜말": f"{master}{img_arti}14artistbadtalk.png",
    # "[아가포항항": f"{master}{img_arti}15artisthahaha.png",
    # "[아가잘자": f"{master}{img_arti}16artistgoodnight.png",
    # "[아가엿": f"{master}{img_arti}17artistfuckyou.png",
    # "[아가붓": f"{master}{img_arti}18artistpainting.png",
    # "[아가붓2": f"{master}{img_arti}18artistpainting1.gif",
    # "[아가붓3": f"{master}{img_arti}18artistpainting2.gif",
    # "[아가붓1": f"{master}{img_arti}18artistpunch.png",
    # "[아가응애": f"{master}{img_arti}19artistunnae.png",
    # "[아가뎃": f"{master}{img_arti}20artistku.png",
    # "[아가볼": f"{master}{img_arti}21몰라.png",
    # "[아가슬퍼": f"{master}{img_arti}22artistsad.png",
    # "[아가빼액2": f"{master}{img_arti}23artistcry.gif",
    # "[아가빼액": f"{master}{img_arti}23artistcryyyying.png",
    # "[아가플렉스": f"{master}{img_arti}24artistflex.png",
    # "[아가플렉스2": f"{master}{img_arti}24artistflexadvan.gif",
    # "[아가볼": f"{master}{img_arti}25artistfocus.png",
    # "[아가땀": f"{master}{img_arti}26artistafraid.png",
    # "[아가영혼": f"{master}{img_arti}27artistnosoul.png",
    # "[아가뀨": f"{master}{img_arti}28artistkuku.png",
    # "[아가뀨2": f"{master}{img_arti}28artistkuku1.gif",
    # "[아가뀨3": f"{master}{img_arti}28artistkuku2.gif",
    # "[아가춤1": f"{master}{img_arti}29artistdance.gif",
    # "[아가춤2": f"{master}{img_arti}29artistdancefast.gif",
    # "[아가춤3": f"{master}{img_arti}29artistdancefastest.gif",
    # "[아가망겜": f"{master}{img_arti}30artistfuckgame.png",
    # "[아가갓겜": f"{master}{img_arti}30artistgodgame.png",
    # "[아가힘내": f"{master}{img_arti}31artistcheerup.png",
    # "[아가이리와": f"{master}{img_arti}32artistpull.png",
    # "[아가물음": f"{master}{img_arti}33artistwhat.png",
    # "[아가어쩔": f"{master}{img_arti}34artistwhatever.png",
    # "[아가저쩔": f"{master}{img_arti}35artistthatever.png",
    # "[아가어쩔서폿": f"{master}{img_arti}35artistwhatbard.gif",
    # "[아가어쩔로아": f"{master}{img_arti}35artistwhatloa.gif",
    # "[아가뾱": f"{master}{img_arti}37artistpok.png",
    # "[아가어허": f"{master}{img_arti}38artisthey.png",
    # "[아가깡": f"{master}{img_arti}38artistkkang.png",
    # "[아가...": f"{master}{img_arti}39artistnocomment.png",
    # "[아가사랑해": f"{master}{img_arti}40artistloveyou.png",
    
    # # 도화가콘 DLC
    # "[아가ㄴㄴ": f"{master}{img_artidlc}10artistno.png",
    # "[아가노양심": f"{master}{img_artidlc}11artistinfinitetry1.png",
    # "[아가노양심2": f"{master}{img_artidlc}12artistkakinsu.png",
    # "[아가무서워": f"{master}{img_artidlc}13artistafraid.png",
    # "[아가그만해": f"{master}{img_artidlc}14artiststop.png",
    # "[아가다망해": f"{master}{img_artidlc}15artistzingergame.png",
    # "[아가다망해2": f"{master}{img_artidlc}16artistzingergame.png",
    # "[아가멸망": f"{master}{img_artidlc}17artistdamm.png",
    # "[아가부활": f"{master}{img_artidlc}18artistagain.png",
    # "[아가굉장해": f"{master}{img_artidlc}19artistamazing.png",
    # "[아가유산": f"{master}{img_artidlc}21artistscouter.png",
    # "[아가님아": f"{master}{img_artidlc}22artistheyyou.png",
    # "[아가ㅁㅊ": f"{master}{img_artidlc}23artistomgcrazy.png",
    # "[아가아가": f"{master}{img_artidlc}24artistbaby.png",
    # "[아가지켜줘": f"{master}{img_artidlc}25artistproitect.png",
    # "[아가컷": f"{master}{img_artidlc}26artistcut.png",
    # "[아가죽어": f"{master}{img_artidlc}27artistdie.png",
    # "[아가쓰레기": f"{master}{img_artidlc}28artisttrash.png",
    # "[아가줘": f"{master}{img_artidlc}29artistgiveme.png",
    # "[아가방긋2": f"{master}{img_artidlc}2artistsmile.png",
    # "[아가더줘": f"{master}{img_artidlc}30artistgivememore.png",
    # "[아가안줘": f"{master}{img_artidlc}31artistnogive.png",
    # "[아가엿": f"{master}{img_artidlc}32artistO.png",
    # "[아가놉": f"{master}{img_artidlc}32artistX.png",
    # "[아가엿": f"{master}{img_artidlc}32artistfuckyou.png",
    # "[아가돔황챠": f"{master}{img_artidlc}33artistdomhcha.png",
    # "[아가뒷담": f"{master}{img_artidlc}34artistbacktalk.png",
    # "[아가뒷담웃음": f"{master}{img_artidlc}35artistboot.png",
    # "[아가뒷모습": f"{master}{img_artidlc}36_.png",
    # "[아가문열어": f"{master}{img_artidlc}36artistopenthedoor.png",
    # "[아가광기웃음": f"{master}{img_artidlc}37artistSMILE.png",
    # "[아가에스더": f"{master}{img_artidlc}4artistesdar.gif",
    # "[아가나만아니면": f"{master}{img_artidlc}5artistnotmelol.png",
    # "[아가나만아니면2": f"{master}{img_artidlc}6artistnotmelol.gif",
    # "[아가몰루": f"{master}{img_artidlc}7artistdontknow.png",
    # "[아가알아와": f"{master}{img_artidlc}8artistfindhow.png",
    # "[아가ㅇㅇ": f"{master}{img_artidlc}9artistyes.png",

    # Special Edition
    "[강선부릅": f"{master}{img_se}kangsun_1.jpg",
    "[강선잠옷": f"{master}{img_se}kangsunHospital.jpg",
    "[속이뻥": f"{master}{img_se}insideOUT.png",
    "[우에엥": f"{master}{img_se}saduaeng.jpg",
    "[뿌엥": f"{master}{img_se}buaeng.jpg",
    "[카멘슈슉": f"{master}{img_se}kamenshushuk.png",
    "[카멘음": f"{master}{img_se}kamenummm.png",
    
    # 신규 사진
    "[검토끼": f"{master}{img_se}blackbunny.png",
    "[카양겔": f"{master}{img_se}cayangkelkel.png",
    "[흑우두뇌": f"{master}{img_se}cowbrain.png",
    "[크로마니움": f"{master}{img_se}cromanyum.png",
    "[두키": f"{master}{img_se}dukiki.png",
    "[하누마탄": f"{master}{img_se}hahanumatan.png",
    "[울면않되": f"{master}{img_se}imnotcry.png",
    "[중나아파": f"{master}{img_se}jungnahurt.png",
    "[쿠크": f"{master}{img_se}kukkk.png",
    "[쿤켈켈": f"{master}{img_se}kunkelkel.png",
    "[오레하": f"{master}{img_se}orehaha.png",
    "[프로켈소개": f"{master}{img_se}prokelintroduce.png",
    "[프로켈": f"{master}{img_se}prokelkel.png",
    "[흰토끼": f"{master}{img_se}whitebunny.png",
    "[요호": f"{master}{img_se}yohoho.png",

    # "[": f"{master}{img_se}.png",
}